[workspace]
members = [
    "crates/floating-odds-exchange-math",
    "programs/floating-odds-exchange",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
basis-points = { version = "0.4.1", default-features = false }
brine-fp = { version = "0.3.1", default-features = false }
solana-math = { version = "0.2.2" }
